# Site settings
title: janstuemmel.de
email: info@janstuemmel.de
description: >
  27 year old programmer. Student at the Technical
  University of Berlin, Computer Science. Interested in Python,
  Javascript and Nodejs.
baseurl: ""
url: "http://janstuemmel.de"
twitter_url: http://twitter.com/janstuemmel
github_url:  http://github.com/janstuemmel

# permalink: /:year/:month/:day/:title

collections:
  slides:
    output: true
    permalink: /:collection/:path

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "about.md"
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "slides"
    values:
      layout: "slides"
